language: java

jdk:
- oraclejdk8
- oraclejdk9
- openjdk7

# skip installation step
install: true

cache:
  directories:
  - $HOME/.m2

script:
- mvn -f com.examples.myproject/pom.xml clean verify -Pjacoco coveralls:report


