language: java

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env: WITH_COVERALLS=true
    - jdk: oraclejdk9
    - jdk: openjdk7
    - os: osx
      osx_image: xcode8

# skip installation step
install: true

cache:
  directories:
  - $HOME/.m2

script:
 - bash -e ./travis_build.sh

